version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - "8432:5432"

  serve:    
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db    
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 8030:8080    
